services:
  api:
    build:
      context: .
      # Target is specified in overrides
    env_file:
      - .env
    environment:
      - PORT=${PORT:-3000}

  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - PORT=${PORT:-3000}
    depends_on:
      - api
